version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: '3.10'
    environment:
      - POSTGRES_DBNAME=app
      - POSTGRES_USERNAME=promise@postgresqlpls
      - POSTGRES_PASSWORD=password@123
      - POSTGRES_HOST=postgresqlpls.postgres.database.azure.com
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - app-static:/app/static
    ports:
      - 8000:8000
  
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    # ports:
    #   - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-static:
  db-data:
